# Generated by Django 6.0.3 on 2026-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id_livre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=100)),
                ('annee_publication', models.IntegerField()),
                ('quantite_disponible', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('emprunté', 'Emprunté'), ('réservé', 'Réservé')], default='disponible', max_length=20)),
            ],
        ),
    ]
